project:
  version: @project.version@

server:
  port:
    8080

spring:
  application:
    name: sprinter-micro
  datasource:
    url: jdbc:h2:mem:sprinter
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true